GET http://localhost:9000/user/getUsers

###

POST http://localhost:9000/user/signUp
content-type: application/json

{
    "userName": "phat",
    "password": "pass",
    "confirmedPassword" : "pass"
}

###
PUT  http://localhost:9000/user/passwordChange

{
    "userName": "phat",
    "password": "pass3"
}